
import React from 'react';
import {
  LayoutSingleColumn,
  LayoutWrapperTopbar,
  LayoutWrapperMain,
  LayoutWrapperFooter,
  Footer,
} from '../../components';

import StaticPage from '../../containers/StaticPage/StaticPage';
import TopbarContainer from '../../containers/TopbarContainer/TopbarContainer';
import image from './Alvar_Aalto_in_his_Studio_1945_web-1536x864.jpeg';
import image2 from './Copy of Untitled Design.png';
import image3 from './www.himassa.com.jpg';
import image4 from './Screenshot 2022-09-25 at 12.44.41.png';
import image5 from './Screenshot 2022-09-25 at 12.56.22.png';
import image6 from './Screenshot 2022-09-25 at 13.00.39.png';
import image7 from './Screenshot 2022-09-25 at 13.03.22.png';
import image8 from './Screenshot 2022-09-25 at 13.05.56.png';
import image9 from './computer.gif';





import css from './BlogPage.module.css';

const BlogPage = () => {
  // prettier-ignore
  return (
    <StaticPage>
      <LayoutSingleColumn>
        <LayoutWrapperTopbar>
          <TopbarContainer />
        </LayoutWrapperTopbar>

        <LayoutWrapperMain className={css.mainWrapper}>
          <h1>BLOG</h1>
          <h1>What is Nordic art?</h1>
        <p>The term "Nordic art" describes the visual culture of the Nordic countries. The origins of Nordic art can be traced back to prehistoric times and Viking art, which was often influenced by mythology. In modern times, artistic movements such as Romanticism and nationalism became increasingly important in Nordic countries' cultural development. Today, Nordic artists are known for their bold use of color and dramatic subject matter. Themes such as nature, identity and spirituality remain central to their work today.</p>

         <h>Nordic art explores the relationship between humans and nature</h>
       <p>The art of the Nordic countries explores themes of nature and the environment, spirituality, mythology, history and culture. It’s also been called “Nordic design” because it often features clean lines, which reflect the minimalist style that was popular in Scandinavian countries during the 20th century.

In recent years this style has been used by artists around the world who want to evoke a sense of timelessness and purity in their work. This includes furniture designers as well as painters and sculptors who incorporate natural materials like wood or stone into their creations.</p>
    
    <h1>Nordic artists are known for their bold...</h1>

    <p>Nordic artists are known for their bold use of color, light and perspective. They also tend to incorporate natural materials like wood or stone into their works.

Nordic artists are known for simple shapes that create strong lines and contrasts. Their subjects are often animals, plants and flowers as well as people that they have observed in everyday life. These subjects may be portrayed with a soft touch or with a more academic style depending on the artist's preference. Many Nordic artists combine several of these techniques in one painting to create an interesting effect.</p>
          <h1>What is original singular art and ai art?</h1>

          <p>Original singular art and ai art are two different types of art that have been gaining popularity in recent years. Both are created by computers, but they differ in their approach to creation.</p>

          <img className={css.coverImage} src={image9} alt="Computer floating

" align="center center" width="300" height="300"  />

<p>Original singular art is created by a computer that uses an algorithm to create its own images, while ai art is created by using an algorithm to analyze existing works and make similar ones based on them.</p>

          <p>Original singular art and ai art are two different ways of creating artwork.

Original singular art is created by hand, with real materials that you can touch and feel. The artist has to think about the composition, color, brush strokes, and more in order to create the piece.

Ai art is computer generated (or "generated by artificial intelligence"). The artist creates a program that can then generate artwork based on certain parameters they set.</p>
          <p>Original singular art, also known as one-of-a-kind art or OOAK, is a type of art that has been made by hand and is not a reproduction. This means that there is only one copy of this particular piece, and it will be unique from every other original piece of art out there.

[Artists] are the people who create original singular art. They can use different mediums to make their work: paint, clay, wood, etc. They often design these pieces themselves and don't use any other artist's work as inspiration for their own creations.

AI Art stands for artificial intelligence art. This type of art uses AI technology to create works that look like they were made by humans but were actually made by computers instead!</p>

          <h1>What is Upcycling?</h1>

          <p>Upcycling represents a variety of processes by which “old” products get to be modified and get a second life as they’re turned into a “new” product. In this way, thanks to the mix and aggregation of used materials, components and items, the end result is a “new product” with more value than the original value of the sum of all its components. In other others, upcycling is about materials or items that get to be re-adapted and/or re-purposed in a creative way, and whose lifespan is, therefore, expanded.
        <p>Art is one of the most important parts of life. It can be used to express emotions, it can be used to make people happy, and it can also be a way to have fun.

Art can also be used as an expression of yourself. When you are creating your art, it allows you to show others what you think or feel about something.

There are many different types of art including: painting, drawing and sculpture. Each type has its own set of rules that must be followed in order for it to be considered "art".

There are many different types of art including: painting, drawing and sculpture. Each type has its own set of rules that must be followed in order for it to be considered "art".</p>
<h1>Other Definitions Of Upcycling</h1>
Upcycling Definition: Richardson’s paper defines upcycling as a way designers can directly reduce the net volume of household solid waste entering the waste stream; and more broadly, net material volumes in the global product market.

Upcycling Definition: Yi et. al. define upcycling as the conversion of waste materials to something useful or valuable, underlining is it a useful concept that can be applied not only to the waste design industry but also to waste recycling and resource circulation

<h1>Examples Of Upcycling</h1>
upcycling definition

Upcycling In Fashion: The production process of the textil industry is complex and needs huge amounts of energy, water, polluting chemicals, among other resources. It’s very polluting to the environment and its supply chain often isn’t an ethical one. Therefore, upcycling comes as a nice solution that’s starting to be developed not only by small artisans but also starting to boom in companies like Patagonia (though more in a re-crafting concept). Damaged clothes no longer fit for wearing are “disassembled” and their textiles get to reused for the creation of some other piece of clothing or as cases, bookmarks or wherever the designer’s creativity takes them.

Upcycling Furniture: It’s about taking old, wasted or broken furniture and re-purposing it. From broken cabinets whose shelves can be screwed into an old door entry door that will work as a decoration piece, or putting some feet supports in a one-side opened bathtub and turning into a sofa: there are no limits to the power of creativity in upcycling furniture and other household items.

Industrial Upcycling: There are established manufacturing organizations reusing the waste in products that re-enter consumer cycles. Examples of this are companies like Terracycle that creates waste collection programs for waste that is impossible or difficult to recycle and ends up producing things like park benches or pencil cases or tote bags from food and drink packaging.

Upcycling And Recycling: What’s The Difference?
The difference between upcycling and recycling is that the latter takes materials like paper, metal, plastic or glass and breaks them down – hence creating a new product (typically of more inferior quality). And as we’ve seen, upcycling doesn’t mean breaking down materials but rather sorting and reusing them in a different, often more fashionable way.

Upcycling And Remanufacturing: What’s The Difference?
According to Richardson, remanufacturing can be understood as a method of extending product lifecycles through reuse and refabrication of products in closed-loop cycles (in other words, contained within a single product line. On the other hand, the goal of upcycling is to refashion and integrate discarded components and materials into a new range of diverse products within open-loop cycles.

<h1>Is Upcycling Eco-Friendly?</h1>The Ecological Value Of Upcycling
If we look at upcycling from a large, scale perspective, we can say that in theory, it contributes to the reduction of CO2 emissions. Not only because the lifetimes of the materials used are extended, but also because there’s, in theory, contributes ultimately to reducing carbon emissions by extending lifetimes of used materials, components and products, and spending less energy in extracting, transforming, new ones or recycling.</p>


          <h1>Must have September finds from our users</h1>
          <p>The evenings are getting darker, time to cozy up with these finds from our site!</p>

          <img className={css.coverImage} src={image5} alt="Notting Hill Shopping Bag" align="center" width="800" height="800"  />




          <a href="https://www.himassa.com/l/the-notting-hill-canvas-shopping-bag/632ec472-07bc-48d8-8096-befee79f9604" align="center" alt="Notting Hill Shopping Bag">Notting Hill Shopping Bag
</a>


<img className={css.coverImage} src={image4} alt="Screenshot 2022-09-25 at 12.44.41.png" align="center" width="800" height="800"  />




          <a href="https://www.himassa.com/l/marc-jacobs-tote-bag/632ec337-9c7d-42aa-a6d1-b7ce85558d31" align="center" alt="Marc Jacobs Totebag">Marc Jacobs Tote Bag 
</a>


<img className={css.coverImage} src={image6} alt="Bruno Mathsson - Chair
" align="center" width="800" height="800"  />

          <a href="https://www.himassa.com/l/bruno-mathsson-chair/632ebe65-3bac-498b-b41c-d9cfa12956c7" align="center" alt="Bruno Mathsson - Chair
">Bruno Mathsson - Chair

</a>



<img className={css.coverImage} src={image7} alt="Sofa Alanda Paolo B&B Italia

" align="center" width="800" height="800"  />

          <a href="https://www.himassa.com/l/sofa-alanda-paolo-bb-italia/632c4216-79b8-4615-a5c4-e0fac595f748" align="center" alt="Sofa Alanda Paolo B&B Italia

">Sofa Alanda Paolo B&B Italia


</a>

<img className={css.coverImage} src={image8} alt="Halo glass 

" align="center center" width="600" height="800"  />

          <a href="https://www.himassa.com/l/halo-glass-2-units-pack/631ee413-d00e-4c20-b35d-dd368dcb9977" align="center" alt="Halo glass 

">Halo glass 


</a>



          
          <h1>What makes your design good design?</h1>
          <img className={css.coverImage} src={image3} alt="www.himassa.com.jpg" align="center" width="800" height="1600"  />
          
         

          <div>
          <h1>TOP  4  ways to succeed as an independent  artist and designer</h1>
          <img className={css.coverImage} src={image2} alt="Copy of Untitled Design.png" align="center" width="800" height="500"  />
          <p>There haven’t been a better time to make a living from your craft. In the recent years multiple tools have been made to help you to earn a living from your craft. In this little blog post we will list a few.</p>

          <h1>1. Social Media</h1>
          

<p>This one is a non-brainer. If you are a creator, you have to put yourself out there.  Luckily with social media you can reach people from around the globe! 

Post photos and videos of your work linking them into your store to make your first sale.</p>

<h1>2. Friends and Family 
</h1>

<p>If you have people around you who have been supporting you, most likely you will make your first sale to this group of people. Let people know what you are doing and most likely you will be sending packages to your friends place very soon.</p>

<h1>3. Podcasts</h1>

<p>You are your own brand. If you follow podcasts that fall into the theme of what you are doing - pitch yourself to the podcast and possibly appear as a guest! This will drive more traffic to you and your brand.</p>

<h1>4. Marketplaces
</h1>

<p>If you want to reach the most amount of people without building your own store and starting from scratch - you can use marketplaces to sell your craft. For example we at Himassa market all products automatically and you can start selling with us freely!</p>






          <h1>Who was Alvar Aalto?</h1>
          <img className={css.coverImage} src={image} alt="Alvar_Aalto_in_his_Studio_1945_web-1536x864.jpeg" align="center" width="800" height="500"  />

            <p> Alvar Aalto, Architect and Artist – that was the name of the first studio which Finnish architect and designer Alvar Aalto opened in 1923, while he was still studying at Helsinki University of Technology. Before that he already had an experience of designing his parents’ entire house. Since then his professional, successful career growth started. 
Soon his first wife, Aino Marsio, also an architect, joined him, so they developed business together. At the same time, they designed their new house in Helsinki, the Villa Aalto. House was designed to be their office as well. Later, during the 1950’s, due to the increased amount of work, Alvar designed separate studio with his second wife, architect Elissa Mäkiniemi.  He named it simply Studio Aalto. Today Villa Aalto is a museum, while the Studio Aalto is in hands of the Alvar Aalto Academy. 
The Pioneer of Nordic Modernism</p>
<p>Among his first architectural works Alvar Aalto included numerous private projects as well, such as family houses and summer houses, but he also successfully worked on functional solutions for business clients. First works, in accordance with his traditional education, were classical. They belonged to Nordic Classicism inspired by national romanticism heritage. 
Besides projects for his family, cousins and friends, he was responsible for several public facilities at the time, such as Jyväskylä Workers’ Club (1925), Jyväskylä Defence Corps building (1926) and Seinäjoki Defence Corp building (1924–1929).
However, Aalto soon turned to more modern design and became one of the pioneers of Nordic Modernism together with architects and designers Arne Jacobsen from Denmark and Arne Korsmo from Norway.
His work became more expressive and more conceptual thus. His Villa Mairea from 1939 was an example of such a design. Significant projects followed, like Baker House within Massachusetts Institute of Technology in the USA (1946-49), and then Säynätsalo Town Hall (1952), Rautatalo office building (1955), Vuoksenniska Church (1959) and Finlandia Hall (1973) in Finland. 
For his contribution to architecture he received numerous awards, among which were Prince Eugen Medal in 1954, RIBA Gold Medal in1957, and AIA Gold Medal in 1963. 
Art Inspired by Nature</p>
<p>During his multi-decade long career Aalto projected more than 200 buildings, but was equally successful as furniture and interior objects designer. Vast number of items that he designed became symbols of Scandinavian modernism and are still in production.
Alvar Aalto found the inspiration in nature and his own surrounding and he was prone to using natural materials. He used to say that every piece of furniture which is directly in contact with human body simply had to be made of natural material. That was one thing he couldn’t compromise with. 
He was excellent with any material that he worked with, whether it was wood, metal, glass or fabric. However he was especially remembered for experimenting with pressing and bending of laminate. Using this technique his items got original, twisted and sculptural shapes. 
“It’s not an art to take and copy everything from tradition or past, it’s necessary to take the material and energy from nature and respond with the work of art, bringing your own psychical energy into it. We are prone to take everything from nature without giving anything in return. That’s not good – it can take a revenge on us.” Alvar Aalto said, as stated in a book Design and designers of the 20th century, written by Radmila Milosavljevic and Marijana Milosavljevic.  
That’s why he, as a contribution to the beauties of nature and inspired by water waves, designed one of the most famous vases in history. It was the glass, wavy Savoy Vase. He designed it together with his wife Aino, for the occasion of opening the Savoy restaurant in Helsinki. The vase delighted everyone. Decorators regarded it as very inspirational, so much that they exposed it as a decoration. On some other instances several vases were put together along their wavy lines, while others were placed with flower bouquets. 
Although it was in 1937, the vase is still one of the most impressive examples of Alvar Aalto’s authentic style. Finnish glass factory Karhula-Littala that produced the Savoy Vase even won the award at the World Exhibition in Paris in 1937, within the International glass exhibition. It was often simply called Aalto Vase and it’s interesting that the word “aalto” in Finnish means “wave” which in this case has multiple symbolism.
The Savoy Vase was later produced in whole spectrum of colors, in different sizes and shapes. It is still produced according to the original Alvar’s design by the same glass factory – Littala from the Finnish town of Littala. 
Between humanism and materialism</p>

<p>As for the furniture design, Alvar Aalto’s approach was under great influence of Bauhaus artists and designers, marked with functionality to a large degree. His solutions were characterized mostly by intuitive design and synthesis of playful and pragmatic ideas. After his honeymoon in Italy, and later Mediterranean journeys, the influence of Renaissance in his work increased.
He liked to use unusual forms, play with sound and light and experiment with materials, but always making the final product functional above all. 
Rational approach to architecture is best seen in his projects for Paimio Sanatorium which was built from 1929 until 1933, as well as Viipuri City Library from 1927 until 1935.  He also designed the interior and all furniture for his architectural solutions, connecting practical and aesthetic side but leaving a personal touch as well.  
That’s how Paimio Chair was made, one of the most famous chairs of Alvar Aalto. The wavy lines of its armrest remind of waviness seen in the Savoy Vase. The seat was made of molded plywood and was skillfully fitted into the frame so it seems like the chair is floating. 
Chairs, armchairs, tables, lamps and other furniture designed by Alvar Aalto have been produced by the Artek Company since 1935. Alvar and Aino Aalto, together with their patron Maire Gullichsen and art historian Nils-Gustav Hahl, founded the Company with a wish to distribute furniture and promote modern living culture through exhibitions and educative programs. Artek is still doing business successfully in Helsinki and Tokyo and is leading a separate platform for furniture restoration.
Alvar Aalto was not only one of the most recognized architects and designers in Europe, but was also extremely appreciated in America. New York Museum of Modern Art (MoMA) organized several exhibitions in his honor. The first one under the name Alvar Aalto: Architecture and Furniture was presented in 1938. In 1984, MoMA organized an exhibition dedicated to his furniture design and glass work –  Alvar Aalto: Furniture and Glass. On centenary of his birth in 1998, a huge retrospective was arranged – Alvar Aalto: Between Humanism and Materialism including original drawings, sketches and architectural models display. </p>
<p>Alvar Aalto – the giant of Finnish nation
With his extreme devotion to urbanism and rational planning, Alvar Aalto left a deep mark on Finnish and Scandinavian architectural scene. The fact that he is considered to be one of the nation’s giants supports this. That’s how Aalto University in Helsinki, founded in 2010 by merging Helsinki University of Technology, Helsinki School of Economics and University of Art and Design Helsinki, got its name in the honor of his contribution to national architecture and urban culture. 
The University’s seat, designed by Alvar Aalto himself, is within the campus in the town of Otaniemi. It consists of six schools with 17,500 students.</p>
<p>On their own initiative, students started the Aalto Design Factory, Aalto Ventures Program and Aalto Entrepreneurship Society (also known as Aaltoes) with the goal to increase the support to students with entrepreneurial ideas who wanted to develop companies of their own. It resulted in numerous innovative solutions and only in few years made Finland become one of the countries with the most developed start-up system in the world. Aalto University set the foundation for experimental education system in a way. It proved to be very successful connecting science, art and business society in Finland and making breeding ground for modern education, multidisciplinary research and progressive development. These are the exact principles on which Alvar Aalto based his whole career.</p>
        

           
          </div>
        </LayoutWrapperMain>

        <LayoutWrapperFooter>
          <Footer />
        </LayoutWrapperFooter>
      </LayoutSingleColumn>
    </StaticPage>
  );
};

export default BlogPage;